.TH nokryptia "1" "June 11, 2021" "Version 1.3.1" "Nokia 5510 Utility"
.SH NAME
nokryptia \- Nokia 5510 Utility
.SH SYNOPSIS
.TP
\fBnokryptia \fR[\fBoptions\fR]\fB file\fR
.SH DESCRIPTION
.PP
nokryptia is a program designed to make mp3 files readable for the Nokia5510,
and to convert them back to mp3 afterwards if needed.
.PP
Normally,
this should be done by the Nokia Audio Manager delivered with your phone,
which will encrypt the mp3's.
.PP
Because the encryption algorithm is not known at this moment,
this application will not encrypt or decrypt the data,
but use a workaround instead.
Because of this,
this utility is extremely fast compared to the application from Nokia.
.SH OPTIONS
.TP
\fB\-u\fR
.TP
\fB\-d\fR
These options convert respectively mp3 into lse and lse into mp3.
The outputfile will be written to the working directory,
so you have to change the working directory to the place where the output file should be written.
.br
If none of these two options is given,
then -u will be taken as default.
It doesn't make sense to combine these two parameters,
if you do this,
only the last one counts.
.TP
\fB\-a <artistname>\fR
.TP
\fB\-t <songtitle>\fR
These options set respectively the artistname and the songtitle that the Nokia 5510 will display.
These options will be ignored if you convert files from lse to mp3.
.br
If these options are not given,
the application will try to read the ID3 tag from the source mp3.
If this is not possible,
it will use the string "unknown",
which is certainly not what you want.
.TP
\fB\-v\fR
Be verbose.
This option gives some more information,
however I don't think it is very useful.
.TP
\fB\-h\fR
Print a short help screen.
.TP
\fBfile\fR
This option is mandatory.
Give the input filename here.
Wildcards are not yet supported.
.SH AUTHOR
Written by Roel Derickx
.TP
ID3 support by Krzysztof Gorgolewski
.TP
Hotplug support by Luigi Paiella
.TP
bugfixes and getopt function calls by Marian Hromiak
.SH COPYRIGHT
Copyright \(co 2002 Roel Derickx.
Copyright \(co 2020 Charlene Wendling.
.br
This is free software; see the source for copying conditions. There is NO
warranty.
